{
  "os": "linux",
  "git": {
    "depth": 5
  },
  "dist": "trusty",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "script": [
    "npm run build",
    "npm run test"
  ],
  "install": "npm i",
  "node_js": "stable",
  "language": "node_js"
}