os: linux
git:
  depth: 5
dist: trusty
cache:
  directories:
  - node_modules
group: stable
script:
- npm run build
- npm run test
install: npm i
node_js: "8.11.3"
language: node_js
deploy:
  provider: heroku
  api_key:
    secure: SkDWpxfVCg/lvCtK35rKYdXPnL5+cKIeZtUEra54qi1sHVyk74123bVVuE3ytjEyGPLUKkTxEbDv6hiqAM9trbx/2gIkH8Xq3WnViFx7qhuyLt+vjUZczzwsst+SryB9fV/fmOQ0h9dG7SSE496Sc/IVyUmebnlXAkXV0wf/wati3M0XL7z2sJT98VC6uw6a9BcoFq1NwfgnW9wi5qE7OR5oVurNpqtXWzlSCZV2x0mOOU7jJQPakJ3HZ9uKgy9S+OX2zhhpTAZ8EdTnDmaTUFYaLjohqdA/xiP7cVZHUU9QPclKqRflZTAR5iAsjwtsHeMqi63WTKW6KcOOex8abHFWMvUf9kDeFuDNcB9WSYoOWKMkoNOI5nOjt6xGF88bgc1GWZw+DWQaS9ypgDiGOb5yRwlBw+BmSTMQWjLpHSGWWuyWPFENyuCguOh99+iPtG6hOBh97j6rkdJHe+oh9mGu+jzS+vE5fKyVM9O016RJGCzNMXqizgwyrDLhyyX8/CyrBubR6aniXVy3+rSAPVjcwjG8dO6GH3wSVCc2kSW6PogpfMKqUrKhE/smdHlZc+VcCe8ObG/HbdmzondNJ+N97/RCuoGdA94f1oxuGvj4b5w7ANJ6bEqTZQ3GZ5dDRZQSDn2nSb17GSlXfpv9mgvQTnewbinHD7klMPzp+14=
  app: client-auth-base
  skip_cleanup: true
  on:
    repo: tkwok/client